name: Upload existing ZIP to Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload existing ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Resourcepack"
          body: "Automatisch aktualisierte ZIP-Datei aus dem Repository."
          files: CopperCraft-Protectet.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
